### ISSUE TITLE
安全客爬取卡在刚运行

### ISSUE THREAD

**Issue by udpsec** [ycdxsb/Security_Articles#1]
运行安全客脚本刚开始就一直卡在下图这个界面，其他家脚本运行良好。不知是不是安全客改结构了
![image](https://user-images.githubusercontent.com/10917718/142748943-9e4e58e6-6f40-441f-8b28-3a9208267906.png)
我ctrl+c强制结束运行显示如下
![image](https://user-images.githubusercontent.com/10917718/142748989-16f00492-6e88-4b27-815a-004f652dba6b.png)

对Python不了解,还麻烦帮忙看看是否安全客改版导致运行卡住。感谢！

**Comment by ycdxsb** [comment]
脚本正常运行，没有问题，可能是网络问题
![image](https://user-images.githubusercontent.com/32149596/142757084-14b6a79a-d306-4a0c-8fc6-1af575df5f88.png)

**Comment by udpsec** [comment]
好的感谢回复，我再尝试一下。
